version: "3"
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm123
    ports:
      - "5432:5432"
    networks:
      - app-network

  product-db:
    image: postgres:11
    container_name: product-db
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm123
    ports:
      - "5433:5432"
    networks:
      - app-network

  sales-db:
    image: mongo:7.0.0
    container_name: sales-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adm123
    ports:
      - "27017:27017"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Porta para comunicação AMQP
      - "15672:15672" # Porta para interface de gerenciamento
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
