version: "1"
services:
  auth-db:
    image: postgres:11
    container_name: auth-db
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm123
    ports:
      - "5432:5432"
    networks:
      - app-network

  product-db:
    image: postgres:11
    container_name: product-db
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adm123
    ports:
      - "5433:5432"
    networks:
      - app-network

  sales-db: # mongodb://admin:admin:adm123@localhost:27017/sales
    image: mongo:7.0.0
    container_name: sales-db
    environment:
      MONGODB_DATABASE: sales
      MONGODB_USER: admin
      MONGODB_PASS: adm123
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
